apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - backup.13.66.88.123.nip.io
    secretName: frontend-tls-secret
  rules:
  - host: backup.13.66.88.123.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /