kind: Deployment
apiVersion: apps/v1
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    app.kubernetes.io/name: zipkin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    app.kubernetes.io/name: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app.kubernetes.io/name: zipkin
